### ISSUE TITLE
Passing in sql instance

### ISSUE THREAD

**Issue by marbemac** [igalklebanov/kysely-postgres-js#6]
Any chance this dialect could allow for optionally passing in a `sql` instance, rather than having the dialect always create it?

The use case here is for when other libraries also need the sql instance (in this case, Lucia Auth https://lucia-auth.com/guidebook/kysely/#postgresql).

**Comment by igalklebanov** [comment]
Hey 👋 

Good idea!

Released in v2.

**Comment by marbemac** [comment]
Thank you!
