### ISSUE TITLE
 `text[]` is being returned as string

### ISSUE THREAD

**Issue by joshxyzhimself** [igalklebanov/kysely-postgres-js#8]
The `scope` with type `text[]` is being returned as string in Kysely. Could it be a problem in this repo, or at Kysely repo?

```ts
const kysely_select = await pg.selectFrom("roles").selectAll().executeTakeFirst();
console.log(JSON.stringify({ kysely_select }, null, 2));

const porsager_postgres_select = await sql`
  SELECT * FROM private.roles;
`;
console.log(JSON.stringify({ porsager_postgres_select }, null, 2));
```

```json
{
  "kysely_select": {
    "id": "cb5c9d7a-15a6-4d9a-bd6d-dac958a3bd03",
    "name": "administrator",
    "scope": "{example,example2}"
  }
}
```

```json
{
  "porsager_postgres_select": [
    {
      "id": "cb5c9d7a-15a6-4d9a-bd6d-dac958a3bd03",
      "name": "administrator",
      "scope": [
        "example",
        "example2"
      ]
    }
  ]
}
```

**Comment by igalklebanov** [comment]
Hey 👋

Kysely doesn't perform any data transformation. The underlying driver is responsible.

What do you get if you run the same query using postgres.js directly?

**Comment by igalklebanov** [comment]
OK, it's a similar issue as the one from discord. I believe reserved connections in postgres.js don't behave exactly like regular connections. As if they don't pull the types to make transformations on results. 

This demands an issue in postgres.js' repository.

**Comment by porsager** [comment]
Looks like we might not get the array types included for the reserved connection. I'll check when I'm back at my computer.
